kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "vsphere-csi-sc"
  labels:
    chart: {{ .Release.Name }}-1.0.0
    release: {{ .Release.Name }}
    heritage: "Helm"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}