kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pvc
  annotations:
    volume.beta.kubernetes.io/storageClassName: "vsphere-csi-sc"
  labels:
    chart: {{ .Release.Name }}-1.0.0
    release: {{ .Release.Name }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}