replicaCount: 1

image:
  repository: michalmikula97/log-saver
  tag: "2.0"
  pullPolicy: IfNotPresent
  imagePullSecrets: 

livenessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 5

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

volumeMounts:
  - mountPath: /code/src/data
    name: logs-storage

volumes:
  - name: logs-storage
    persistentVolumeClaim:
      claimName: log-saver-pvc

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  path: /
  issuerName: letsencrypt-staging
  host: demo.app.t82.yunex.dev

pvc:
  storage: "1Gi"